---
title: "Manual_Sift_Corpus"
author: "Boyana Buyuklieva"
date: "August 1, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(stringr)
library(ggplot2)

path <- 'C:/Users/billi/Dropbox/_PhD/__PhD Book/Writing Drafts/_Februrary_Draft/Chapter_2_scholar'
```

```{r, cache=TRUE }
sifted <- read_excel(paste0(path,"./Final_Data/Excel/seedcorpus_sifted_cleaned.xlsx"),
    na = "NA",
    col_types = c("numeric", "text", "text", 
        "text", "text", "text", 
        "text", "skip", "numeric", "numeric", 
        "numeric", "numeric", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", "numeric"))

#do not add anything
sifted$horizontalDepth <- NULL
sifted$`Paper Reviewed`<- NULL



names(sifted)
#queries start from 6
```

#	Which queries lost most?
```{r}
#	Which queries lost most?
removed <- subset(sifted, grepl("N", sifted$`Pass 2`), drop = TRUE)

#replace rank with 1s
removed[,6:16] <- apply(removed[,6:16], 2, function(x) ifelse(!is.na(as.numeric(x)),1,0) )

droped <- data.frame(count = sort(colSums(removed[,6:16]), decreasing = T))
droped$query = rownames(droped )

droped
```

#	Which papers hit most queries?

```{r}
sifted_bool <- sifted
sifted_bool[,6:16] <- apply(sifted_bool[,6:16], 2, function(x) ifelse(!is.na(x),1,0) )

hits <- data.frame(count = sort(rowSums(sifted_bool[,6:16]), decreasing = T))
hits <- cbind (sifted_bool[,c('title')], hits)

print('Most papers hit only one query:')
summary(as.factor(hits$count))


print('The ones that covered most are:')
head(hits[,c('title','count')], 8)
```


#	How much do queries overlap?
```{r}
#for every column, record co-ocuring query hits in a matrix

qpairMatches <- data.frame()
rep = 10#numebr of queries
for(start in 6:15){
  for (end in 1:rep) {
      increment = start + end
       #print( paste(start , ':', increment))
       tmp <- sifted_bool[,start]+ sifted_bool[,increment]
       tmp <- data.frame(colnames(sifted_bool[,start]), colnames(sifted_bool[,increment]), count = sum(tmp == 2))
       qpairMatches <- rbind(qpairMatches,tmp)
  }
  rep = rep - 1
}

```

#	What does this overlap look like?
```{r}
qpairMatches[order(-qpairMatches$count),]
```


```{r}
suppressPackageStartupMessages(library(circlize))
#https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html#chord-diagram-colors
#remeber to cite!
#://medialab.github.io/iwanthue/
#set grid.col

chordDiagram(unique(qpairMatches[qpairMatches$count>0,]), 
             transparency = .20 )
circos.clear()
```
